### ISSUE TITLE
Redundant arguments BODY_NAMES

### ISSUE THREAD

**Issue by YiranXu** [nyu-cds/dov205_assignment3#4] opened 2017-02-17 19:37 UTC
The"advance" and "report_energy" functions both pass arguments "BODY_NAMES". However, there is already an argument called "BODIES" which passes as a local variable. We might be able to just call BODIES.keys to get BODY_NAMES.

**Comment by dataframing** [comment] 2017-02-17 20:05
This is intended behavior. Calling `BODIES.keys()` within both `advance()` and `report_energy()` would incur a minor cost, but multiplied by 10,000 loops it becomes more noticeable.

Without polluting the global namespace and reducing performance, it isn't easy to get around the redundant arguments. I agree that it would be ideal to avoid weaving `BODY_NAMES` through both functions, but it's either that or incur runtime cost.

**Comment by dataframing** [comment] 2017-02-17 22:45
Closing.

**Closed as completed by dataframing** 2017-02-17 22:45 UTC
